import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// * 动态路由
// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }



// * 平行路由
// export default function RootLayout({ children, team, analytics }) {
//     return (
//         <html>
//             <body className="p-6">
//                 <div className="p-10 mb-6 bg-sky-600 text-white rounded-xl">
//                     Parallel Routes Examples
//                 </div>

//                 <nav className="flex items-center justify-center gap-10 text-blue-600 mb-6">
//                     <Link href="/">Home</Link>
//                     <Link href="/page-views">Page Views</Link>
//                     <Link href="/visitors">Visitors</Link>
//                 </nav>

//                 <div className="flex gap-6">
//                     {team}
//                     {analytics}
//                 </div>

//                 {children}
//             </body>
//         </html>
//     );
// }





// * 拦截路由
export default function Layout({ children, modal }) {
    console.log('------children', children, modal)
    
    return (
        <html>
            <body>
                {children}

                {modal}
            </body>
        </html>
    );
}
