/**
 * * 根布局
 * 
 * app 目录必须包含根布局，也就是 app/layout.js 这个文件是必需的。
 * 根布局必须包含 html 和 body标签，其他布局不能包含这些标签。如果你要更改这些标签，不推荐直接修改，参考《Metadata 篇》。
 * 你可以使用 路由组 创建多个根布局。
 * 默认根布局是服务端组件，且不能设置为客户端组件。
 * 
 * metadata: https://juejin.cn/book/7307859898316881957/section/7309079119902277669
 * 路由组：https://juejin.cn/book/7307859898316881957/section/7308693561648611379#heading-5
 * 服务端组件：https://juejin.cn/book/7307859898316881957/section/7309076661532622885
 */
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>{children}</body>
        </html>
    );
}
