import { Inter } from "next/font/google";
import StyledJsxRegistry from './registry'
import StyledComponentsRegistry from './lib/registry'
import "./globals.css";

// * 外部样式表
// 不过要注意，该外部包必须是从 npm 包直接导入或者下载完和你的代码放在一起。
// import 'bootstrap/dist/css/bootstrap.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            {/* cdn引入 */}
            {/* <head>
                <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" />
            </head> */}

            {/* <body>{children}</body> */}

            <body>
                {/* <StyledJsxRegistry>{children}</StyledJsxRegistry> */}
                <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
            </body>
        </html>
    );
}
